version: '3'
services:

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sit
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /opt/mysql_data:/var/lib/mysql