export const START_LOAD = 'START_LOAD'
export const FINISH_LOAD = 'FINISH_LOAD'

export const MODAL_START_LOAD = 'MODAL_START_LOAD'
export const MODAL_FINISH_LOAD = 'FINISH_START_LOAD'


export const CARTRIDGES_LOAD_SUCCESS = 'CARTRIDGES_LOAD_SUCCESS'
export const CARTRIDGES_PRINTER_LOAD_SUCCESS = 'CARTRIDGES_PRINTER_LOAD_SUCCESS'
export const CARTRIDGE_LOAD_SUCCESS = 'CARTRIDGE_LOAD_SUCCESS'
export const CARTRIDGE_NEW = 'CARTRIDGE_NEW'
export const CARTRIDGE_ORDER_SUCCESS = 'CARTRIDGE_ORDER_SUCCESS'
export const CARTRIDGE_SAVE_SUCCESS = 'CARTRIDGE_SAVE_SUCCESS'

export const PRINTERS_LOAD_SUCCESS = 'PRINTERS_LOAD_SUCCESS'

export const COLOR_CARTRIDGES_LOAD_SUCCESS = 'COLOR_CARTRIDGES_LOAD_SUCCESS'