export const START_LOAD = 'START_LOAD'
export const FINISH_LOAD = 'FINISH_LOAD'

export const CARTRIDGES_START_LOAD = 'CARTRIDGES_START_LOAD'
export const CARTRIDGES_FINISH_LOAD = 'CARTRIDGES_FINISH_LOAD'
export const CARTRIDGES_LOAD_SUCCESS = 'CARTRIDGES_LOAD_SUCCESS'
export const CARTRIDGE_LOAD_SUCCESS = 'CARTRIDGE_LOAD_SUCCESS'
export const CARTRIDGE_NEW = 'CARTRIDGE_NEW'

export const PRINTERS_LOAD_SUCCESS = 'PRINTERS_LOAD_SUCCESS'