test:
    path: /test
    controller: App\Controller\HomeController::test
    methods: GET
apiOrderCartridge:
    path: /api/cartridge/order
    controller: App\Controller\Api\CartridgeController::order
    methods: POST
apiSaveCartridge:
    path: /api/cartridge/save
    controller: App\Controller\Api\CartridgeController::save
    methods: POST
apiNewCartridge:
    path: /api/cartridge/save
    controller: App\Controller\Api\CartridgeController::new
    methods: PUT
apiCartridgeById:
    path: /api/cartridge/{id}
    controller: App\Controller\Api\CartridgeController::getCartridgeById
    methods: GET
apiCartridges:
    path: /api/cartridges
    controller: App\Controller\Api\CartridgeController::cartridges
    methods: GET
apiPrinterCartridges:
    path: /api/printer/{id}/cartridges
    controller: App\Controller\Api\PrinterController::printerCartridges
    methods: GET
apiCartridgeColor:
    path: /api/cartridge/color/all
    controller: App\Controller\Api\ColorCartridgeController::getAllColor
    methods: GET
apiPrinters:
    path: /api/printers
    controller: App\Controller\Api\PrinterController::printers
    methods: GET
all:
    path: /{req}
    controller: App\Controller\HomeController::index
    requirements:
        req: ".*"