test:
    path: /test/{id}/{rr}
    controller: App\Controller\HomeController::test
    methods: GET
apiCartridges:
    path: /api/cartridges
    controller: App\Controller\Api\CartridgeController::cartridges
    methods: GET
all:
    path: /{req}
    controller: App\Controller\HomeController::index
    requirements:
        req: ".*"