test:
    path: /test
    controller: App\Controller\HomeController::test
    methods: GET
apiCartridges:
    path: /api/cartridges
    controller: App\Controller\Api\CartridgeController::cartridges
    methods: GET
apiOrderCartridge:
    path: /api/cartridge/{id}/order
    controller: App\Controller\Api\CartridgeController::order
    methods: POST
apiPrinterCartridges:
    path: /api/printer/{id}/cartridges
    controller: App\Controller\Api\PrinterController::printerCartridges
    methods: GET
apiPrinters:
    path: /api/printers
    controller: App\Controller\Api\PrinterController::printers
    methods: GET
all:
    path: /{req}
    controller: App\Controller\HomeController::index
    requirements:
        req: ".*"